import { Partner } from "./routes/_app.partners";

export const PARTNERS_DATA: Partner[] = [
    {
        id: 1,
        name: "Colour Coffee",
        path_name: "colour_coffee",
        logo: "/logos/colour_coffee.jpg",
        description:
            "Colour Coffee is a coffee roasting company that specializes in creating high-quality coffee beans from sustainable and ethically sourced coffee beans.",
        marketCap: 1000000000,
        tradeVolume: 50000000,
        category: "Exchange",
        country: "USA",
    },
    {
        id: 2,
        name: "Page Turners",
        path_name: "page_turners",
        logo: "/logos/page_turners.jpg",
        description: "A small, welcoming bookstore offering new and used books.",
        marketCap: 2000000000,
        tradeVolume: 100000000,
        category: "Exchange",
        country: "USA",
    },
    {
        id: 3,
        name: "Pure Wellness Apothecary",
        path_name: "wellness",
        logo: "/logos/pwa.jpg",
        description:
            "Pure Wellness Apothecary is a wellness center that offers a variety of services, including massage, acupuncture, and chiropractic care.",
        marketCap: 3000000000,
        tradeVolume: 150000000,
        category: "Exchange",
        country: "USA",
    },
    {
        id: 4,
        name: "Happy Paws Grooming",
        path_name: "happy_paws",
        logo: "/logos/happy_paws.jpg",
        description:
            "Happy Paws Grooming is a grooming company that offers a variety of services, including haircuts, coloring, and styling.",
        marketCap: 4000000000,
        tradeVolume: 200000000,
        category: "Exchange",
        country: "USA",
    },
    {
        id: 5,
        name: "Artful Expressions Gallery",
        path_name: "artful_expressions",
        logo: "/logos/ae.jpg",
        description: "Artful Expressions Gallery is a gallery that showcases contemporary art exhibitions.",
        marketCap: 5000000000,
        tradeVolume: 250000000,
        category: "Exchange",
        country: "USA",
    },
    {
        id: 6,
        name: "Silver Screen Cinema",
        path_name: "silver_screen",
        logo: "/logos/silver_screen.jpg",
        description: "Silver Screen Cinema is a cinema that offers a variety of films and documentaries.",
        marketCap: 6000000000,
        tradeVolume: 300000000,
        category: "Exchange",
        country: "USA",
    },
    {
        id: 7,
        name: "Bloom & Co.",
        path_name: "bloom",
        logo: "/logos/bloom.jpg",
        description: "Bloom & Co. is a modern florist with unique arrangements for every occasion.",
        marketCap: 7000000000,
        tradeVolume: 350000000,
        category: "Exchange",
        country: "USA",
    },
    {
        id: 8,
        name: "Sunny Side Bistro",
        path_name: "sunny_side",
        logo: "/logos/sunny_side.jpg",
        description: "Sunny Side Bistro is a bistro specializing in hearty breakfast plates and light lunches.",
        marketCap: 8000000000,
        tradeVolume: 400000000,
        category: "Exchange",
        country: "USA",
    },
];
